#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasteMakerPull.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TasteMaker")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGuestlist(Guestlist instance);
    partial void UpdateGuestlist(Guestlist instance);
    partial void DeleteGuestlist(Guestlist instance);
    partial void InsertListing(Listing instance);
    partial void UpdateListing(Listing instance);
    partial void DeleteListing(Listing instance);
    partial void InsertEvent(Event instance);
    partial void UpdateEvent(Event instance);
    partial void DeleteEvent(Event instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::TasteMakerPull.Properties.Settings.Default.TasteMakerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Guestlist> Guestlists
		{
			get
			{
				return this.GetTable<Guestlist>();
			}
		}
		
		public System.Data.Linq.Table<Listing> Listings
		{
			get
			{
				return this.GetTable<Listing>();
			}
		}
		
		public System.Data.Linq.Table<Event> Events
		{
			get
			{
				return this.GetTable<Event>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Universe.Guestlist")]
	public partial class Guestlist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GuestlistId;
		
		private string _id;
		
		private System.Nullable<System.DateTime> _updated_at;
		
		private string _token;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private string _state;
		
		private string _Buyer_id;
		
		private string _Buyer_email;
		
		private string _Buyer_name;
		
		private string _Attendee_id;
		
		private string _Attendee_email;
		
		private string _Attendee_name;
		
		private System.Nullable<decimal> _TicketType_price;
		
		private string _TicketType_name;
		
		private string _TicketType_id;
		
		private string _Order_id;
		
		private string _Order_discount_code;
		
		private string _Order_currency;
		
		private string _Listing_id;
		
		private string _Listing_title;
		
		private string _Event_id;
		
		private System.Nullable<int> _Event_start_stamp;
		
		private System.Nullable<int> _Event_end_stamp;
		
		private string _Answer_name;
		
		private string _Answer_value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGuestlistIdChanging(int value);
    partial void OnGuestlistIdChanged();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    partial void OntokenChanging(string value);
    partial void OntokenChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnBuyer_idChanging(string value);
    partial void OnBuyer_idChanged();
    partial void OnBuyer_emailChanging(string value);
    partial void OnBuyer_emailChanged();
    partial void OnBuyer_nameChanging(string value);
    partial void OnBuyer_nameChanged();
    partial void OnAttendee_idChanging(string value);
    partial void OnAttendee_idChanged();
    partial void OnAttendee_emailChanging(string value);
    partial void OnAttendee_emailChanged();
    partial void OnAttendee_nameChanging(string value);
    partial void OnAttendee_nameChanged();
    partial void OnTicketType_priceChanging(System.Nullable<decimal> value);
    partial void OnTicketType_priceChanged();
    partial void OnTicketType_nameChanging(string value);
    partial void OnTicketType_nameChanged();
    partial void OnTicketType_idChanging(string value);
    partial void OnTicketType_idChanged();
    partial void OnOrder_idChanging(string value);
    partial void OnOrder_idChanged();
    partial void OnOrder_discount_codeChanging(string value);
    partial void OnOrder_discount_codeChanged();
    partial void OnOrder_currencyChanging(string value);
    partial void OnOrder_currencyChanged();
    partial void OnListing_idChanging(string value);
    partial void OnListing_idChanged();
    partial void OnListing_titleChanging(string value);
    partial void OnListing_titleChanged();
    partial void OnEvent_idChanging(string value);
    partial void OnEvent_idChanged();
    partial void OnEvent_start_stampChanging(System.Nullable<int> value);
    partial void OnEvent_start_stampChanged();
    partial void OnEvent_end_stampChanging(System.Nullable<int> value);
    partial void OnEvent_end_stampChanged();
    partial void OnAnswer_nameChanging(string value);
    partial void OnAnswer_nameChanged();
    partial void OnAnswer_valueChanging(string value);
    partial void OnAnswer_valueChanged();
    #endregion
		
		public Guestlist()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestlistId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GuestlistId
		{
			get
			{
				return this._GuestlistId;
			}
			set
			{
				if ((this._GuestlistId != value))
				{
					this.OnGuestlistIdChanging(value);
					this.SendPropertyChanging();
					this._GuestlistId = value;
					this.SendPropertyChanged("GuestlistId");
					this.OnGuestlistIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(50)")]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="VarChar(50)")]
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buyer_id", DbType="VarChar(50)")]
		public string Buyer_id
		{
			get
			{
				return this._Buyer_id;
			}
			set
			{
				if ((this._Buyer_id != value))
				{
					this.OnBuyer_idChanging(value);
					this.SendPropertyChanging();
					this._Buyer_id = value;
					this.SendPropertyChanged("Buyer_id");
					this.OnBuyer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buyer_email", DbType="VarChar(50)")]
		public string Buyer_email
		{
			get
			{
				return this._Buyer_email;
			}
			set
			{
				if ((this._Buyer_email != value))
				{
					this.OnBuyer_emailChanging(value);
					this.SendPropertyChanging();
					this._Buyer_email = value;
					this.SendPropertyChanged("Buyer_email");
					this.OnBuyer_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buyer_name", DbType="VarChar(50)")]
		public string Buyer_name
		{
			get
			{
				return this._Buyer_name;
			}
			set
			{
				if ((this._Buyer_name != value))
				{
					this.OnBuyer_nameChanging(value);
					this.SendPropertyChanging();
					this._Buyer_name = value;
					this.SendPropertyChanged("Buyer_name");
					this.OnBuyer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attendee_id", DbType="VarChar(50)")]
		public string Attendee_id
		{
			get
			{
				return this._Attendee_id;
			}
			set
			{
				if ((this._Attendee_id != value))
				{
					this.OnAttendee_idChanging(value);
					this.SendPropertyChanging();
					this._Attendee_id = value;
					this.SendPropertyChanged("Attendee_id");
					this.OnAttendee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attendee_email", DbType="VarChar(50)")]
		public string Attendee_email
		{
			get
			{
				return this._Attendee_email;
			}
			set
			{
				if ((this._Attendee_email != value))
				{
					this.OnAttendee_emailChanging(value);
					this.SendPropertyChanging();
					this._Attendee_email = value;
					this.SendPropertyChanged("Attendee_email");
					this.OnAttendee_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attendee_name", DbType="VarChar(50)")]
		public string Attendee_name
		{
			get
			{
				return this._Attendee_name;
			}
			set
			{
				if ((this._Attendee_name != value))
				{
					this.OnAttendee_nameChanging(value);
					this.SendPropertyChanging();
					this._Attendee_name = value;
					this.SendPropertyChanged("Attendee_name");
					this.OnAttendee_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketType_price", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> TicketType_price
		{
			get
			{
				return this._TicketType_price;
			}
			set
			{
				if ((this._TicketType_price != value))
				{
					this.OnTicketType_priceChanging(value);
					this.SendPropertyChanging();
					this._TicketType_price = value;
					this.SendPropertyChanged("TicketType_price");
					this.OnTicketType_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketType_name", DbType="VarChar(50)")]
		public string TicketType_name
		{
			get
			{
				return this._TicketType_name;
			}
			set
			{
				if ((this._TicketType_name != value))
				{
					this.OnTicketType_nameChanging(value);
					this.SendPropertyChanging();
					this._TicketType_name = value;
					this.SendPropertyChanged("TicketType_name");
					this.OnTicketType_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketType_id", DbType="VarChar(50)")]
		public string TicketType_id
		{
			get
			{
				return this._TicketType_id;
			}
			set
			{
				if ((this._TicketType_id != value))
				{
					this.OnTicketType_idChanging(value);
					this.SendPropertyChanging();
					this._TicketType_id = value;
					this.SendPropertyChanged("TicketType_id");
					this.OnTicketType_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_id", DbType="VarChar(50)")]
		public string Order_id
		{
			get
			{
				return this._Order_id;
			}
			set
			{
				if ((this._Order_id != value))
				{
					this.OnOrder_idChanging(value);
					this.SendPropertyChanging();
					this._Order_id = value;
					this.SendPropertyChanged("Order_id");
					this.OnOrder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_discount_code", DbType="VarChar(50)")]
		public string Order_discount_code
		{
			get
			{
				return this._Order_discount_code;
			}
			set
			{
				if ((this._Order_discount_code != value))
				{
					this.OnOrder_discount_codeChanging(value);
					this.SendPropertyChanging();
					this._Order_discount_code = value;
					this.SendPropertyChanged("Order_discount_code");
					this.OnOrder_discount_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_currency", DbType="VarChar(50)")]
		public string Order_currency
		{
			get
			{
				return this._Order_currency;
			}
			set
			{
				if ((this._Order_currency != value))
				{
					this.OnOrder_currencyChanging(value);
					this.SendPropertyChanging();
					this._Order_currency = value;
					this.SendPropertyChanged("Order_currency");
					this.OnOrder_currencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Listing_id", DbType="VarChar(50)")]
		public string Listing_id
		{
			get
			{
				return this._Listing_id;
			}
			set
			{
				if ((this._Listing_id != value))
				{
					this.OnListing_idChanging(value);
					this.SendPropertyChanging();
					this._Listing_id = value;
					this.SendPropertyChanged("Listing_id");
					this.OnListing_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Listing_title", DbType="VarChar(50)")]
		public string Listing_title
		{
			get
			{
				return this._Listing_title;
			}
			set
			{
				if ((this._Listing_title != value))
				{
					this.OnListing_titleChanging(value);
					this.SendPropertyChanging();
					this._Listing_title = value;
					this.SendPropertyChanged("Listing_title");
					this.OnListing_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Event_id", DbType="VarChar(50)")]
		public string Event_id
		{
			get
			{
				return this._Event_id;
			}
			set
			{
				if ((this._Event_id != value))
				{
					this.OnEvent_idChanging(value);
					this.SendPropertyChanging();
					this._Event_id = value;
					this.SendPropertyChanged("Event_id");
					this.OnEvent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Event_start_stamp", DbType="Int")]
		public System.Nullable<int> Event_start_stamp
		{
			get
			{
				return this._Event_start_stamp;
			}
			set
			{
				if ((this._Event_start_stamp != value))
				{
					this.OnEvent_start_stampChanging(value);
					this.SendPropertyChanging();
					this._Event_start_stamp = value;
					this.SendPropertyChanged("Event_start_stamp");
					this.OnEvent_start_stampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Event_end_stamp", DbType="Int")]
		public System.Nullable<int> Event_end_stamp
		{
			get
			{
				return this._Event_end_stamp;
			}
			set
			{
				if ((this._Event_end_stamp != value))
				{
					this.OnEvent_end_stampChanging(value);
					this.SendPropertyChanging();
					this._Event_end_stamp = value;
					this.SendPropertyChanged("Event_end_stamp");
					this.OnEvent_end_stampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer_name", DbType="VarChar(50)")]
		public string Answer_name
		{
			get
			{
				return this._Answer_name;
			}
			set
			{
				if ((this._Answer_name != value))
				{
					this.OnAnswer_nameChanging(value);
					this.SendPropertyChanging();
					this._Answer_name = value;
					this.SendPropertyChanged("Answer_name");
					this.OnAnswer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer_value", DbType="VarChar(50)")]
		public string Answer_value
		{
			get
			{
				return this._Answer_value;
			}
			set
			{
				if ((this._Answer_value != value))
				{
					this.OnAnswer_valueChanging(value);
					this.SendPropertyChanging();
					this._Answer_value = value;
					this.SendPropertyChanged("Answer_value");
					this.OnAnswer_valueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Universe.Listing")]
	public partial class Listing : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ListingId;
		
		private string _id;
		
		private string _slug;
		
		private string _title;
		
		private string _state;
		
		private string _description;
		
		private string _category_id;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private System.Nullable<System.DateTime> _updated_at;
		
		private System.Nullable<decimal> _price;
		
		private string _capacity;
		
		private System.Nullable<bool> _has_active_discount_codes;
		
		private string _rate_type;
		
		private string _events_headline;
		
		private string _host_headline;
		
		private string _base_currency;
		
		private string _src_currency;
		
		private System.Nullable<bool> _is_active;
		
		private string _event_id;
		
		private string _cost_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnListingIdChanging(int value);
    partial void OnListingIdChanged();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnslugChanging(string value);
    partial void OnslugChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Oncategory_idChanging(string value);
    partial void Oncategory_idChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OncapacityChanging(string value);
    partial void OncapacityChanged();
    partial void Onhas_active_discount_codesChanging(System.Nullable<bool> value);
    partial void Onhas_active_discount_codesChanged();
    partial void Onrate_typeChanging(string value);
    partial void Onrate_typeChanged();
    partial void Onevents_headlineChanging(string value);
    partial void Onevents_headlineChanged();
    partial void Onhost_headlineChanging(string value);
    partial void Onhost_headlineChanged();
    partial void Onbase_currencyChanging(string value);
    partial void Onbase_currencyChanged();
    partial void Onsrc_currencyChanging(string value);
    partial void Onsrc_currencyChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    partial void Onevent_idChanging(string value);
    partial void Onevent_idChanged();
    partial void Oncost_idChanging(string value);
    partial void Oncost_idChanged();
    #endregion
		
		public Listing()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListingId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ListingId
		{
			get
			{
				return this._ListingId;
			}
			set
			{
				if ((this._ListingId != value))
				{
					this.OnListingIdChanging(value);
					this.SendPropertyChanging();
					this._ListingId = value;
					this.SendPropertyChanged("ListingId");
					this.OnListingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(200)")]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slug", DbType="VarChar(200)")]
		public string slug
		{
			get
			{
				return this._slug;
			}
			set
			{
				if ((this._slug != value))
				{
					this.OnslugChanging(value);
					this.SendPropertyChanging();
					this._slug = value;
					this.SendPropertyChanged("slug");
					this.OnslugChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(200)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(200)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="VarChar(200)")]
		public string category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacity", DbType="VarChar(MAX)")]
		public string capacity
		{
			get
			{
				return this._capacity;
			}
			set
			{
				if ((this._capacity != value))
				{
					this.OncapacityChanging(value);
					this.SendPropertyChanging();
					this._capacity = value;
					this.SendPropertyChanged("capacity");
					this.OncapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_active_discount_codes", DbType="Bit")]
		public System.Nullable<bool> has_active_discount_codes
		{
			get
			{
				return this._has_active_discount_codes;
			}
			set
			{
				if ((this._has_active_discount_codes != value))
				{
					this.Onhas_active_discount_codesChanging(value);
					this.SendPropertyChanging();
					this._has_active_discount_codes = value;
					this.SendPropertyChanged("has_active_discount_codes");
					this.Onhas_active_discount_codesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate_type", DbType="VarChar(200)")]
		public string rate_type
		{
			get
			{
				return this._rate_type;
			}
			set
			{
				if ((this._rate_type != value))
				{
					this.Onrate_typeChanging(value);
					this.SendPropertyChanging();
					this._rate_type = value;
					this.SendPropertyChanged("rate_type");
					this.Onrate_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_events_headline", DbType="VarChar(MAX)")]
		public string events_headline
		{
			get
			{
				return this._events_headline;
			}
			set
			{
				if ((this._events_headline != value))
				{
					this.Onevents_headlineChanging(value);
					this.SendPropertyChanging();
					this._events_headline = value;
					this.SendPropertyChanged("events_headline");
					this.Onevents_headlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host_headline", DbType="VarChar(MAX)")]
		public string host_headline
		{
			get
			{
				return this._host_headline;
			}
			set
			{
				if ((this._host_headline != value))
				{
					this.Onhost_headlineChanging(value);
					this.SendPropertyChanging();
					this._host_headline = value;
					this.SendPropertyChanged("host_headline");
					this.Onhost_headlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_base_currency", DbType="VarChar(200)")]
		public string base_currency
		{
			get
			{
				return this._base_currency;
			}
			set
			{
				if ((this._base_currency != value))
				{
					this.Onbase_currencyChanging(value);
					this.SendPropertyChanging();
					this._base_currency = value;
					this.SendPropertyChanged("base_currency");
					this.Onbase_currencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_src_currency", DbType="VarChar(200)")]
		public string src_currency
		{
			get
			{
				return this._src_currency;
			}
			set
			{
				if ((this._src_currency != value))
				{
					this.Onsrc_currencyChanging(value);
					this.SendPropertyChanging();
					this._src_currency = value;
					this.SendPropertyChanged("src_currency");
					this.Onsrc_currencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
		public System.Nullable<bool> is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_id", DbType="VarChar(200)")]
		public string event_id
		{
			get
			{
				return this._event_id;
			}
			set
			{
				if ((this._event_id != value))
				{
					this.Onevent_idChanging(value);
					this.SendPropertyChanging();
					this._event_id = value;
					this.SendPropertyChanged("event_id");
					this.Onevent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost_id", DbType="VarChar(200)")]
		public string cost_id
		{
			get
			{
				return this._cost_id;
			}
			set
			{
				if ((this._cost_id != value))
				{
					this.Oncost_idChanging(value);
					this.SendPropertyChanging();
					this._cost_id = value;
					this.SendPropertyChanged("cost_id");
					this.Oncost_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Universe.Event")]
	public partial class Event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EventId;
		
		private string _id;
		
		private System.Nullable<int> _start_stamp;
		
		private System.Nullable<int> _end_stamp;
		
		private string _tz;
		
		private string _state;
		
		private string _listing_id;
		
		private System.Nullable<System.DateTime> _start_time;
		
		private System.Nullable<System.DateTime> _end_time;
		
		private System.Nullable<bool> _full;
		
		private System.Nullable<bool> _read_only;
		
		private System.Nullable<bool> _has_active_payment_plan;
		
		private System.Nullable<bool> _can_use_sepa;
		
		private System.Nullable<bool> _alternative_payment_methods;
		
		private System.Nullable<int> _count_attending;
		
		private string _host_id;
		
		private string _capacity_ids;
		
		private string _rate_ids;
		
		private string _payment_plan_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Onstart_stampChanging(System.Nullable<int> value);
    partial void Onstart_stampChanged();
    partial void Onend_stampChanging(System.Nullable<int> value);
    partial void Onend_stampChanged();
    partial void OntzChanging(string value);
    partial void OntzChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void Onlisting_idChanging(string value);
    partial void Onlisting_idChanged();
    partial void Onstart_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_timeChanged();
    partial void Onend_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onend_timeChanged();
    partial void OnfullChanging(System.Nullable<bool> value);
    partial void OnfullChanged();
    partial void Onread_onlyChanging(System.Nullable<bool> value);
    partial void Onread_onlyChanged();
    partial void Onhas_active_payment_planChanging(System.Nullable<bool> value);
    partial void Onhas_active_payment_planChanged();
    partial void Oncan_use_sepaChanging(System.Nullable<bool> value);
    partial void Oncan_use_sepaChanged();
    partial void Onalternative_payment_methodsChanging(System.Nullable<bool> value);
    partial void Onalternative_payment_methodsChanged();
    partial void Oncount_attendingChanging(System.Nullable<int> value);
    partial void Oncount_attendingChanged();
    partial void Onhost_idChanging(string value);
    partial void Onhost_idChanged();
    partial void Oncapacity_idsChanging(string value);
    partial void Oncapacity_idsChanged();
    partial void Onrate_idsChanging(string value);
    partial void Onrate_idsChanged();
    partial void Onpayment_plan_idChanging(string value);
    partial void Onpayment_plan_idChanged();
    #endregion
		
		public Event()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(200)")]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_stamp", DbType="Int")]
		public System.Nullable<int> start_stamp
		{
			get
			{
				return this._start_stamp;
			}
			set
			{
				if ((this._start_stamp != value))
				{
					this.Onstart_stampChanging(value);
					this.SendPropertyChanging();
					this._start_stamp = value;
					this.SendPropertyChanged("start_stamp");
					this.Onstart_stampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_stamp", DbType="Int")]
		public System.Nullable<int> end_stamp
		{
			get
			{
				return this._end_stamp;
			}
			set
			{
				if ((this._end_stamp != value))
				{
					this.Onend_stampChanging(value);
					this.SendPropertyChanging();
					this._end_stamp = value;
					this.SendPropertyChanged("end_stamp");
					this.Onend_stampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tz", DbType="VarChar(200)")]
		public string tz
		{
			get
			{
				return this._tz;
			}
			set
			{
				if ((this._tz != value))
				{
					this.OntzChanging(value);
					this.SendPropertyChanging();
					this._tz = value;
					this.SendPropertyChanged("tz");
					this.OntzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(200)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listing_id", DbType="VarChar(200)")]
		public string listing_id
		{
			get
			{
				return this._listing_id;
			}
			set
			{
				if ((this._listing_id != value))
				{
					this.Onlisting_idChanging(value);
					this.SendPropertyChanging();
					this._listing_id = value;
					this.SendPropertyChanged("listing_id");
					this.Onlisting_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this.Onstart_timeChanging(value);
					this.SendPropertyChanging();
					this._start_time = value;
					this.SendPropertyChanged("start_time");
					this.Onstart_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[full]", Storage="_full", DbType="Bit")]
		public System.Nullable<bool> full
		{
			get
			{
				return this._full;
			}
			set
			{
				if ((this._full != value))
				{
					this.OnfullChanging(value);
					this.SendPropertyChanging();
					this._full = value;
					this.SendPropertyChanged("full");
					this.OnfullChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_read_only", DbType="Bit")]
		public System.Nullable<bool> read_only
		{
			get
			{
				return this._read_only;
			}
			set
			{
				if ((this._read_only != value))
				{
					this.Onread_onlyChanging(value);
					this.SendPropertyChanging();
					this._read_only = value;
					this.SendPropertyChanged("read_only");
					this.Onread_onlyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_active_payment_plan", DbType="Bit")]
		public System.Nullable<bool> has_active_payment_plan
		{
			get
			{
				return this._has_active_payment_plan;
			}
			set
			{
				if ((this._has_active_payment_plan != value))
				{
					this.Onhas_active_payment_planChanging(value);
					this.SendPropertyChanging();
					this._has_active_payment_plan = value;
					this.SendPropertyChanged("has_active_payment_plan");
					this.Onhas_active_payment_planChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_can_use_sepa", DbType="Bit")]
		public System.Nullable<bool> can_use_sepa
		{
			get
			{
				return this._can_use_sepa;
			}
			set
			{
				if ((this._can_use_sepa != value))
				{
					this.Oncan_use_sepaChanging(value);
					this.SendPropertyChanging();
					this._can_use_sepa = value;
					this.SendPropertyChanged("can_use_sepa");
					this.Oncan_use_sepaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alternative_payment_methods", DbType="Bit")]
		public System.Nullable<bool> alternative_payment_methods
		{
			get
			{
				return this._alternative_payment_methods;
			}
			set
			{
				if ((this._alternative_payment_methods != value))
				{
					this.Onalternative_payment_methodsChanging(value);
					this.SendPropertyChanging();
					this._alternative_payment_methods = value;
					this.SendPropertyChanged("alternative_payment_methods");
					this.Onalternative_payment_methodsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count_attending", DbType="Int")]
		public System.Nullable<int> count_attending
		{
			get
			{
				return this._count_attending;
			}
			set
			{
				if ((this._count_attending != value))
				{
					this.Oncount_attendingChanging(value);
					this.SendPropertyChanging();
					this._count_attending = value;
					this.SendPropertyChanged("count_attending");
					this.Oncount_attendingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host_id", DbType="VarChar(200)")]
		public string host_id
		{
			get
			{
				return this._host_id;
			}
			set
			{
				if ((this._host_id != value))
				{
					this.Onhost_idChanging(value);
					this.SendPropertyChanging();
					this._host_id = value;
					this.SendPropertyChanged("host_id");
					this.Onhost_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacity_ids", DbType="VarChar(200)")]
		public string capacity_ids
		{
			get
			{
				return this._capacity_ids;
			}
			set
			{
				if ((this._capacity_ids != value))
				{
					this.Oncapacity_idsChanging(value);
					this.SendPropertyChanging();
					this._capacity_ids = value;
					this.SendPropertyChanged("capacity_ids");
					this.Oncapacity_idsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate_ids", DbType="VarChar(200)")]
		public string rate_ids
		{
			get
			{
				return this._rate_ids;
			}
			set
			{
				if ((this._rate_ids != value))
				{
					this.Onrate_idsChanging(value);
					this.SendPropertyChanging();
					this._rate_ids = value;
					this.SendPropertyChanged("rate_ids");
					this.Onrate_idsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_plan_id", DbType="VarChar(MAX)")]
		public string payment_plan_id
		{
			get
			{
				return this._payment_plan_id;
			}
			set
			{
				if ((this._payment_plan_id != value))
				{
					this.Onpayment_plan_idChanging(value);
					this.SendPropertyChanging();
					this._payment_plan_id = value;
					this.SendPropertyChanged("payment_plan_id");
					this.Onpayment_plan_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
